<?php
$arr = [
  "Pay Now",
  "Useful Links",
  "Privacy & TOS",
  "Preview Deposit",
  "Home",
  "Gateway",
  "Name",
  "Amount",
  "Charge",
  "Payable amount",
  "Confirm",
  "Deposit",
  "Currency",
  "Select Payment Method",
  "Details",
  "Sent/Received Money",
  "Search",
  "Sender",
  "Receiver",
  "Sent/Received Money List",
  "Create Security Pin",
  "Receiver E-Mail",
  "Transaction ID",
  "Requested Amount",
  "Type",
  "Status",
  "Created time",
  "Sent",
  "Received",
  "Success",
  "Pending",
  "Minimum Amount",
  "E-mail",
  "Min Amount",
  "Maximum Amount",
  "Transaction Date",
  "Select Currency",
  "All Type",
  "Dispute List",
  "Dispute For",
  "Dispute ID",
  "Action",
  "Escrow",
  "Open",
  "Created Date",
  "No data found",
  "Solved",
  "Close",
  "View",
  "Admin",
  "All Status",
  "You are muted",
  "Type Here",
  "Upload File",
  "File",
  "Issue has been solved by",
  "Issue has been closed by",
  "have been muted by",
  "have been unmuted by",
  "Preview Escrow",
  "Request Amount",
  "Percentage Charge",
  "Fixed Charge",
  "Total Charge",
  "Receivable Amount",
  "Note",
  "Security Pin",
  "eg:12345",
  "Please enter your security PIN",
  "Escrow Request",
  "Recipient email or username",
  "Please enter valid email or username",
  "Create escrow request",
  "Available Balance",
  "Min Request Limit",
  "Max Request Limit",
  "Escrow lists",
  "Generated",
  "Deposited",
  "Request for payment",
  "Payment Disbursed",
  "Canceled",
  "Send Payout Request",
  "accept this request",
  "accept this request?",
  "Hold",
  "Dispute",
  "Refunded",
  "N/A",
  "Escrow payment",
  "Percentage charge",
  "Fixed charge",
  "Total charge",
  "View Dispute Details",
  "Payment disbursed",
  "Request Payment",
  "Cancel",
  "request for payment disbursed?",
  "request for payment?",
  "Escrow Payment",
  "Accept",
  "cancel this request?",
  "Confirmation",
  "Are you sure you want to",
  "Confirmed",
  "Confirm Exchange",
  "Exchange",
  "From",
  "Select from wallet",
  "No Currency Available",
  "Exchange Rate",
  "You will get",
  "Exchange Money",
  "From Wallet",
  "To Wallet",
  "Transaction Details",
  "Exchange rate",
  "Remaining Balance",
  "Updated Balance",
  "Select From Currency",
  "Select To Currency",
  "Exchange Amount",
  "Completed",
  "Fund Added List",
  "Min Deposit Limit",
  "Max Deposit Limit",
  "New Balance",
  "Payable Amount",
  "Transfer Charge",
  "Add Fund",
  "Method",
  "All Currency",
  "developed by",
  "Ohh No",
  "Are you sure you want to logout",
  "Logout",
  "Logo",
  "Manage Content",
  "Login Now",
  "Dashboard",
  "Features",
  "Fund added List",
  "Send Money",
  "Transfer List",
  "Pending List",
  "Request Money",
  "Request Money List",
  "New Request",
  "All Request",
  "All Exchange",
  "Redeem",
  "Generate New Code",
  "Generated List",
  "Pending list",
  "Insert Redeem Code",
  "Create a request",
  "Escrow List",
  "Voucher",
  "Create voucher",
  "Voucher List",
  "Payout",
  "Send Request",
  "Request Payout",
  "Payout List",
  "Transactions",
  "Security PIN",
  "Tickets",
  "Result",
  "Language",
  "flag",
  "Notifications",
  "Commission List",
  "Settings Panel",
  "Two Factor",
  "Manage PIN uses",
  "Security question\'s answer",
  "Reset Security Pin",
  "Alerts Center",
  "Clear all",
  "No notification found",
  "Change Password",
  "SMS Verification",
  "Profile",
  "Resend code",
  "Pay with",
  "Your Card Information",
  "Enter your card number",
  "Enter the name on your card",
  "Submit",
  "Didn\'t get Code? Click to get",
  "Payment Preview",
  "PLEASE SEND EXACTLY",
  "TO",
  "SCAN TO SEND",
  "Mercado Pago Payment",
  "Pay via Monnify",
  "Pay with PAYPAL",
  "Stripe Payment",
  "Pay with VoguePay",
  "Choose File",
  "Payout Method",
  "Charge Amount",
  "Total Payable",
  "Request user",
  "Paid by",
  "Payment Done",
  "Payout method list",
  "Choose a payout method",
  "Back",
  "Enter Amount",
  "Continue",
  "Withdraw",
  "Min limit",
  "Max limit",
  "Your full name",
  "City",
  "You",
  "Enter your city",
  "Phone",
  "Referral Link",
  "Enter your phone number",
  "State",
  "Enter your state",
  "Select language to get notification on preferred language",
  "Address",
  "Generate Redeem",
  "Enter your address",
  "Choose profile picture",
  "Update Profile",
  "Current Balance",
  "Current balance",
  "Generate redeem",
  "Receiver will received",
  "Charge deduct from",
  "Confirm Request",
  "Redeem Generate",
  "Generate Redeem Code",
  "Generate redeem code",
  "Receiver will pay the txn charge",
  "Generate",
  "Redeem code",
  "Redeem cods",
  "Unused",
  "Used",
  "Redeem Code",
  "Submit redeem code",
  "Redeem codes",
  "Confirm Transfer",
  "Transfer limit",
  "Transfer",
  "RequestMoney",
  "RedeemCode",
  "Yes",
  "Are you sure you want to cancel",
  "New Ticket",
  "Subject",
  "Ticket#",
  "Message",
  "0.00",
  "Choose files",
  "Submit Ticket",
  "Tickets Log",
  "Create new ticket",
  "Last Reply",
  "Answered",
  "Replied",
  "Closed",
  "No Data Found",
  "Ticket",
  "Transaction List",
  "Customer Replied",
  "File(s)",
  "file(s) selected",
  "Are you want to close ticket",
  "Receiver name",
  "Create Security pin",
  "Security Question",
  "Answer",
  "Security question answer",
  "Hints",
  "In future helps you guess the answer",
  "Security pin confirmation",
  "Create security PIN",
  "Manage pin uses",
  "Save Changes",
  "Reset security pin",
  "Old security pin",
  "eg:1234",
  "Confirm pin",
  "Reset Security PIN",
  "Reset security PIN",
  "Preview Voucher Request",
  "Voucher Create",
  "Recipient email",
  "or username",
  "Please enter valid email",
  "Voucher Lists",
  "Voucher lists",
  "Payment done",
  "Sender request to payment disburse",
  "Min Payment Limit",
  "Voucher Payment",
  "Max Payment Limit",
  "Voucher payment",
  "Requester Name",
  "Confirm Payment",
  "Cancel Payment",
  "Payment Failed",
  "Sorry",
  "No result found",
  "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
  "it seems some issue in server to server communication. Kindly connect with administrator",
  "Go Back to Home",
  "Copyright",
  "Copy",
  "All rights reserved by",
  "All Rights Reserved",
  "You are logged in",
  "Payment Success",
  "THANK YOU",
  "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being wi ▶",
  "Current password",
  "Enter your current password",
  "Password",
  "Email",
  "Email Verification",
  "Confirm New Password",
  "New Password",
  "Enter new password",
  "Repeat password",
  "Confirm Password",
  "Please confirm your password before continuing",
  "Forgot Your Password",
  "User | Reset Password",
  "Reset Password",
  "Enter Email",
  "Send Password Reset Link",
  "Create an Account",
  "Already have an account",
  "Login",
  "all terms and condition",
  "I accept",
  "Your Phone Number",
  "Enter Referral",
  "Sign Up",
  "Don't have an account?",
  "Username or Email",
  "Sign In",
  "Sign In To Your Account",
  "Username Or Email Address",
  "Remember Me",
  "Don\'t have an account",
  "Sing up",
  "Create Your Account",
  "Enter Full Name",
  "Enter Email Address",
  "Enter Username",
  "Repeat Password",
  "Create Account",
  "Sing in",
  "User | Verify E-Mail",
  "Verify Your Email Address",
  "A fresh verification link has been sent to your email address.",
  "Before proceeding, please check your email for a verification link. If you did not receive the email.",
  "click here to request another",
  "Subscribe",
  "PRIVACY & TOS",
  "Advertiser Agreement",
  "Acceptable policy",
  "Privacy Policy",
  "Technology privacy",
  "Developer Agreement",
  "Quick Links",
  "About",
  "Our Performance",
  "Help",
  "FAQ",
  "Blog",
  "Gateways",
  "Total Wallet",
  "Total Currency",
  "Total Users",
  "Contact",
  "To",
  "Level",
  "Title",
  "hero-banner",
  "Your Message",
  "Your Subject",
  "Your Email",
  "Contact Us",
  "Blog-image",
  "About Us",
  "Read More",
  "image",
  "More",
  "Happy Clients",
  "Weekly Transaction",
  "Monthly Transaction",
  "Yearly Transaction",
  "Blog Details",
  "Popular Posts",
  "Send Message",
  "Download On",
  "App Store",
  "to",
  "Google Play",
  "Logo Update",
  "Short Descriptions",
  "add-fund-short-description",
  "deposit-short-description",
  "payout-short-description",
  "redeem-code-short-description",
  "request-money-short-description",
  "send-money-short-description",
  "voucher-payment-short-description",
  "escrow-short-description",
  "exchange-money-short-description",
  "If enable transaction charge will deduct from receiver",
  "User Wallet Balance",
  "Total",
  "Sender E-Mail",
  "Preview Add Fund",
  "Balance",
  "Request Received",
  "Request Sent",
  "User Send Money Summary",
  "Last 30 Days Send Money",
  "Last 7 Days Send Money",
  "Today Send Money",
  "Transaction Summary",
  "Last 30 days charge",
  "This month transactions summary",
  "User Request Money Summary",
  "This Year Request Money",
  "Last 30 Days Request Money",
  "Last 7 Days Request Money",
  "Today Request Money",
  "User Voucher Payment Summary",
  "User Redeem & Voucher Summary",
  "Last 30 Days Redeem Money",
  "Last 30 Days Voucher Money",
  "This Year Voucher Payment",
  "Last 30 Days Voucher Payment",
  "Last 7 Days Voucher Payment",
  "Today Voucher Payment",
  "2 Step Security",
  "Two Factor Authenticator",
  "Disable Two Factor Authenticator",
  "Enable Two Factor Authenticator",
  "Google Authenticator",
  "Use Google Authenticator to Scan the QR code  or use the code",
  "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
  "DOWNLOAD APP",
  "Verify Your OTP",
  "Authenticator Code",
  "Enter Google Authenticator Code",
  "Verify",
  "2 FA Code",
  "You have information to submit in verification center.",
  "Submit Now",
  "Welcome",
  "We are delighted to have you, and we hope you will have a great stay with us!",
  "Add money",
  "Money Out",
  "Bill Payment",
  "Qr code",
  "Download",

];
return $arr;
